select * from customer

--Q1. What is the total revenue generated by male vs female customer?
SELECT
    "Gender",
    SUM("Purchase Amount (USD)") AS total_revenue
FROM customer
GROUP BY "Gender";



--Q2. Which customers used a discount but stil spent more than the average purchase amount?
SELECT
    "Customer ID",
    "Gender",
    "Item Purchased",
    "Purchase Amount (USD)"
FROM customer
WHERE "Discount Applied" = 'Yes'
AND "Purchase Amount (USD)" >
(
    SELECT AVG("Purchase Amount (USD)")
    FROM customer
);
--Q3. Which are the top5 products with the highest average review rating ?
SELECT
    "Item Purchased",
    AVG("Review Rating") AS avg_rating
FROM customer
GROUP BY "Item Purchased"
ORDER BY avg_rating DESC
LIMIT 5;
--Q4. Compare the average Purchase Amounts between Standard and Express Shipping.

SELECT
    "Shipping Type",
    AVG("Purchase Amount (USD)") AS avg_purchase_amount
FROM customer
WHERE "Shipping Type" IN ('Standard', 'Express')
GROUP BY "Shipping Type";


--Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.

SELECT
    "Subscription Status",
    AVG("Purchase Amount (USD)") AS average_spend,
    SUM("Purchase Amount (USD)") AS total_revenue
FROM customer
GROUP BY "Subscription Status";



--Q6. Which products have the highest percentage of purchases with discounts applied?
SELECT
    "Item Purchased",
    ROUND(
        100.0 * SUM(
            CASE
                WHEN "Discount Applied" = 'Yes' THEN 1
                ELSE 0
            END
        ) / COUNT(*),
        2
    ) AS discount_percentage
FROM customer
GROUP BY "Item Purchased"
ORDER BY discount_percentage DESC;




--Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.

SELECT
    customer_segment,
    COUNT(*) AS customer_count
FROM
(
    SELECT
        CASE
            WHEN "Previous Purchases" = 0 THEN 'New'
            WHEN "Previous Purchases" BETWEEN 1 AND 5 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM customer
) t
GROUP BY customer_segment;




--Q8. What are the top 3 most purchased products within each category?

WITH product_counts AS
(
    SELECT
        "Category",
        "Item Purchased",
        COUNT(*) AS purchase_count,
        RANK() OVER
        (
            PARTITION BY "Category"
            ORDER BY COUNT(*) DESC
        ) AS rank_num
    FROM customer
    GROUP BY "Category", "Item Purchased"
)
SELECT
    "Category",
    "Item Purchased",
    purchase_count
FROM product_counts
WHERE rank_num <= 3
ORDER BY "Category", purchase_count DESC;





--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT
    "Subscription Status",
    COUNT(*) AS customer_count,
    ROUND(
        100.0 * COUNT(*) /
        SUM(COUNT(*)) OVER (),
        2
    ) AS percentage
FROM customer
WHERE "Previous Purchases" > 5
GROUP BY "Subscription Status";




--Q10. What is the revenue contribution of each age group?

SELECT
    age_group,
    SUM("Purchase Amount (USD)") AS total_revenue,
    ROUND(
        100.0 * SUM("Purchase Amount (USD)") /
        SUM(SUM("Purchase Amount (USD)")) OVER (),
        2
    ) AS revenue_percentage
FROM
(
    SELECT
        CASE
            WHEN "Age" BETWEEN 18 AND 25 THEN '18-25'
            WHEN "Age" BETWEEN 26 AND 35 THEN '26-35'
            WHEN "Age" BETWEEN 36 AND 45 THEN '36-45'
            WHEN "Age" BETWEEN 46 AND 55 THEN '46-55'
            ELSE '56+'
        END AS age_group,
        "Purchase Amount (USD)"
    FROM customer
) t
GROUP BY age_group
ORDER BY age_group;


select version();
